version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    ports: ["9093:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Инициализация топиков
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on: [kafka]
    command: |
      bash -c "
        echo 'Waiting for Kafka to be ready...'
        sleep 30
        
        # Создаем топики с большим количеством партиций
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic tasks --partitions 10 --replication-factor 1
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --topic results --partitions 10 --replication-factor 1
        
        echo 'Topics created:'
        kafka-topics --list --bootstrap-server kafka:9092
        
        # Держим контейнер живым для зависимостей
        sleep infinity
      "

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports: ["8080:8080"]
    depends_on: [kafka-init]
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on: [kafka-init]
    restart: unless-stopped

networks:
  default:
    driver: bridge 